#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount sv dnf flatpak updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner" \
  bat="batw" \
  less="lessw"

alias \
  ls="exa --icons" \
  l="ls -la" \
	grep="rg" \
	diff="diff --color=auto" \

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	e="$EDITOR" \
	v="$EDITOR" \
  oracle='gqlplus "dirxml/epumhbu@(DESCRIPTION=(LOAD_BALANCE=on) (ADDRESS=(PROTOCOL=TCP)(HOST= tlvx8m-scan1.nice.com) (PORT=1521)) (CONNECT_DATA=(SERVICE_NAME=oraprd)))"'

alias \
	lf="lfub" \
  alias svn="svn --config-dir $XDG_CONFIG_HOME/subversion"
