#!/bin/sh

# run every time bspwm restarts
picom -b --config ~/.config/picom.conf --experimental-backends &
feh --bg-fill ~/.local/wallpaper2.png &
# xinput --set-prop 26 336 0.5
# run once
startup_lock_file=/tmp/bspwm-startup.lock
if [ ! -f $startup_lock_file ]; then
  toggle_headphones
	touch $startup_lock_file

  setxkbmap -option caps:escape &
  tint2 &
	autorandr --change &
  bspm -d &
  sxhkd -c ~/.config/sxhkd/sxhkdrc.bspwm &
	xsetroot -cursor_name left_ptr &
  /usr/libexec/polkit-gnome-authentication-agent-1 &
  xrdb ~/.Xresources
	numlockx on &
  nm-applet --indicator &
	blueman-applet &
  pasystray &
	# xfce4-power-manager &
	ksuperkey &
  easystroke &
  # bspi_listen --config ~/.config/bspwm/bspi.ini &
	# flashfocus &
  # davmail &
  clipster -d &
  dunst &
  bspswallow &
  # start_noise_canceling &
  # xautolock -time 15 -locker "cmatrixlock-bspwm" -detectsleep &

  # tint2 fix for fullscreen
  xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" $(xdo id -n tint2)
fi


bspc config single_monocle false

monitors=$(bspc query -M)
while read monitor; do
  bspc monitor "$monitor" -d 1 2 3 4 5 6 7 8 9
done <<< "$monitors"

# monitors
# I=1
# M=$(bspc query -M | wc -l)
# if [ "$M" = 1 ]; then
#   bspc monitor -d 1 2 3 4 5 6 7 8 9

  # if [ $(bspc query -M --names) = "eDP1" ]; then 
    # bspc config single_monocle true
  # fi
# elif [ "$M" = 2 ]; then

# else
#   bspc monitor $(bspc query -M | awk NR==1) -d 1 2 3 4 5 6 7 8 9
#   bspc monitor $(bspc query -M | awk NR==2) -d 1 2 3 4 5 6 7 8 9

# elif [ "$M" = 3 ]; then
#   bspc monitor $(bspc query -M | awk NR==1) -d 1 2 3 4 5
#   bspc monitor $(bspc query -M | awk NR==2) -d 1 2 3 4
#   bspc monitor $(bspc query -M | awk NR==3) -d 1 2 3 4
# elif [ "$M" = 4 ]; then
#   bspc monitor $(bspc query -M | awk NR==1) -d 1 2 3
#   bspc monitor $(bspc query -M | awk NR==2) -d 4 5 6
#   bspc monitor $(bspc query -M | awk NR==3) -d 7 8
#   bspc monitor $(bspc query -M | awk NR==4) -d 9 10
# elif [ "$M" = 5 ]; then
#   bspc monitor $(bspc query -M | awk NR==1) -d 1 2
#   bspc monitor $(bspc query -M | awk NR==2) -d 3 4
#   bspc monitor $(bspc query -M | awk NR==3) -d 5 6
#   bspc monitor $(bspc query -M | awk NR==4) -d 7 8
#   bspc monitor $(bspc query -M | awk NR==5) -d 9 10
# fi

bspc config remove_unplugged_monitors     true
bspc config border_width                  4
window_gap=15
if [[ -z $(bspc query -M --names | grep DP-1) ]]; then
  window_gap=10
fi
bspc config window_gap                    $window_gap
bspc config top_padding                   26
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config split_ratio                   0.60
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_follows_pointer         true
# bspc config pointer_follows_focus         true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
# bspc config ignore_ewmh_fullscreen all

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# colors
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	        "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"

# floating rules
bspc rule -r "*"
bspc rule -a Java state=floating
bspc rule -a zoom state=floating
bspc rule -a Galculator state=floating
# bspc rule -a Galculator state=floating
bspc rule -a "Apache Directory Studio" rectangle=1000x680+0+0 center=true
bspc rule -a "Brave-browser:pop-up" state=floating
