#!/bin/sh

# run every time bspwm restarts
picom -b --config ~/.config/picom.conf --experimental-backends &
feh --bg-fill --no-fehbg ~/.local/wallpaper2.png &
killall deadd-notification-center; deadd-notification-center &

#run once
startup_lock_file=/tmp/bspwm-startup.lock
if [ ! -f $startup_lock_file ]; then
  touch $startup_lock_file
  mkdir /tmp/opal
  # latte-dock &
  setxkbmap -option caps:escape &
  tint2 &
	autorandr --change &
  bspm -d &
  sxhkd &
	xsetroot -cursor_name left_ptr &
  /usr/libexec/polkit-gnome-authentication-agent-1 &
  xrdb ~/.config/x11/xresources &
	numlockx on &
  nm-applet --indicator &
	blueman-applet &
  pasystray &
	ksuperkey &
  # easystroke &
  # bspi_listen --config ~/.config/bspwm/bspi.ini &
  clipster -d &
  # dunst &
  bspswallow &
  unclutter &
  xscreensaver --no-splash &
  # bspwm_clean_monocle &
  kbdd &
  dbus-update-activation-environment --systemd XDG_CURRENT_DESKTOP="KDE" &
  systemctl --user stop xdg-desktop-portal{,-gtk} &
  pkill -f xdg-desktop-portal &
  # killall xdg-desktop-portal && XDG_CURRENT_DESKTOP="KDE" /usr/libexec/xdg-desktop-portal-kde && XDG_CURRENT_DESKTOP="KDE" /usr/libexec/xdg-desktop-portal &
  alttab -bg "#3B4252" -fg "#ECEFF4" -frame "#597AA0" -font "xft:JetBrains Mono Nerd Font Mono-10" -t 250x140 -i 250x64 -theme "Papirus-dark" -w 1 -mk Super_L &
fi


monitors=$(bspc query -M)
echo "$monitors" > /tmp/monitors
while read monitor; do
  bspc monitor "$monitor" -d 1 2 3 4 5 6 7 8 9
done <<< "$monitors"


if [[ -z $(bspc query -M --names | grep -w DP-1) ]]; then
  echo "no DP-1"
  # Set all to monocle
  bspc query -D | xargs -I {} bspc desktop {} -l monocle
  bspc config remove_unplugged_monitors     false
  bspc config remove_disabled_monitors      false
else
  echo "yes DP-1"
  # Set all to tiling

  bspc query -D | xargs -I {} bspc desktop {} -l tiled
  bspc config remove_unplugged_monitors     true
  bspc config remove_disabled_monitors      true
fi
bspc config window_gap                    10
# bspc config -m DP-1 window_gap            15

bspc config external_rules_command ~/.local/bin/bspwm_external_rules
bspc config single_monocle false
bspc config border_width                  4
bspc config top_padding                   26
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config split_ratio                   0.60
# bspc config borderless_monocle            true
# bspc config gapless_monocle               true
bspc config borderless_monocle            false
bspc config gapless_monocle               false
bspc config focus_follows_pointer         true
# bspc config pointer_follows_focus         true
# bspc config remove_unplugged_monitors     false
# bspc config remove_disabled_monitors      false
bspc config merge_overlapping_monitors    true
bspc config pointer_motion_interval       1
# bspc config hide_by_moving                true
# bspc config ignore_ewmh_fullscreen all

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# colors
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	        "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"

# floating rules
bspc rule -r "*"
bspc rule -a "*" center=true
bspc rule -a Java state=floating
bspc rule -a zoom state=floating
bspc rule -a lattedock center=false state=floating border=off
bspc rule -a Galculator state=floating
bspc rule -a kcalc state=floating
bspc rule -a "persepolis" state=floating
